### ISSUE TITLE
Draft extract offset

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-deadline#10]
Having multiple extractors operating on the same data, seems to overwrite each other.

Solution atm is offsetting the extractors, but this is very intuitive, so need a solution for simultaneous execution. Adding a "deadlineDraftTemplate" data member might be best.

**Comment by mottosso** [comment]
Did you mean "unintuitive"? Could you outline what each extractor is meant to be doing?

**Comment by tokejepsen** [comment]
> Did you mean "unintuitive"?

yes, sorry.

> Could you outline what each extractor is meant to be doing?

Will do when I get around to the documentation

**Comment by mottosso** [comment]
> Will do when I get around to the documentation

:)

Trust me, it will help you figure out what to do. Something like this will suffice.

- Delete data `deadlineVersion`
- Read `deadlineVersion`
- Find and add Deadline version to `deadlineVersion`

Try making it a habit to document *before* you implement. Sounds crazy, but it's a proven technique.

- http://tom.preston-werner.com/2010/08/23/readme-driven-development.html
- http://collectiveidea.com/blog/archives/2014/04/21/on-documentation-driven-development/

It's a precursor to this.

- http://en.wikipedia.org/wiki/Test-driven_development

**Comment by tokejepsen** [comment]
ftrack extractor is offset, so both extractors work easily
