### ISSUE TITLE
remove validate_deadline_output_existence 

### ISSUE THREAD

**Issue by mkolar** [pyblish/pyblish-deadline#11]
I'd say that plugins like this should probably not be a part of extension. It's not really doing anything related to deadline and is only necessary in some hosts. For example, nuke needs folder created before rendering, but houdini creates them on the fly. This means that every single time we publish, it fails, we have to repair and run publish again. 

How about we either remove it, or move it out of the plugins folder to 'optional' or the 'examples' folder. that way it would stay available if user wants to put it in their studio plugins, is not in the way for general deadline extension.

**Comment by tokejepsen** [comment]
Sure, thats sounds good.

**Comment by mkolar** [comment]
Actually going through it. I think there are more candidates for the same treatment. validate_output_location, validate_render_order, bot of these are 1. workflow specific, 2. not required for the extension to run successfully. Great if included as example for people of how they can work with the data created by extension, but probably shouldn't be a part of the core plugins for the extension

**Comment by tokejepsen** [comment]
How about a validator for the existence of a frame string ei. "####" or "%04d"?

Its on my list of things to do, as this will break deadline or you will be rendering to the same file for an entire sequence.

**Comment by mkolar** [comment]
Not sure about this one. We often send single frame renders to farm (and many other studios do too), so that wouldn't have frame string and naturally fail such validator. I can see why you want to include it, I just think that these extensions should be fairly minimal by default, with any extra functionality being optional.

**Comment by mottosso** [comment]
You know this better than I, but wouldn't (shouldn't?) single frames still include the frame they are supposed to be rendering? E.g. `my_shot_f100.exr`

**Comment by mkolar** [comment]
not really. we do a lot of promo materials to go along with the show. posters, elements for posters, single character poses. most of those don't use frame numbers at all.

**Comment by mottosso** [comment]
Ah, that makes sense.

**Comment by tokejepsen** [comment]
How about only validating for frame string if there are multiple images to be rendered in an instance?

**Comment by mkolar** [comment]
That might be reasonable. Even though I still think that it is not necessary successfully send to deadline. 

How about we split the plugins into 2 folders. 'core' and 'optional', where core is all you need to be able to publish to deadline and optional gives you a variation of helpful validators.

**Comment by mottosso** [comment]
> How about we split the plugins into 2 folders. 'core' and 'optional', where core is all you need to be able to publish to deadline and optional gives you a variation of helpful validators.

Keep it simple guys. The extension is purely about Deadline, and not about workflow. If you've got things in mind specific for a particular workflow, make it another extension.

**Comment by tokejepsen** [comment]
> Keep it simple guys. The extension is purely about Deadline, and not about workflow. If you've got things in mind specific for a particular workflow, make it another extension.

That is a good point. I do want to keep it a simple as possible, but in my head an extension should help towards a successful publish, with a plug'n'play method.

**Comment by mkolar** [comment]
I'm more with @mottosso on this. Hence the issue in the first place. Any plugins like this might be useful to user to show them how they can work on top of the extension, but don't do anything in terms of functionality.

**Comment by tokejepsen** [comment]
> For example, nuke needs folder created before rendering, but houdini creates them on the fly

How about we have the ```validate_deadline_output_existence``` only for nuke? Since this will fail on the farm when submitting from nuke. Or would you classify this still as a workflow feature?

**Comment by mkolar** [comment]
For nuke it makes sense since folders need to exist for successful render.

**Comment by mkolar** [comment]
I just realized this would mean one slight change. Currently final output location is used to store deadline job and plugin files. Which actually make sense. So we can either leave the `validate_output_existence' in there to make sure we have a place to save these files, or we could have them created in a temp location as the default deadline plugin does it.

**Comment by tokejepsen** [comment]
Yeah, I would vote for putting them in the temp directory and possibly even delete them when done with them, as the submission parameters are in the monitor?

**Comment by tokejepsen** [comment]
fixed in #15
