### ISSUE TITLE
Create job per instance

### ISSUE THREAD

**Issue by mkolar** [pyblish/pyblish-deadline#12]
We should be storing and creating deadline job, per instance.

Currently job_data get's appended to context, which however means, that every instance to be rendered, gets the same job_data, even though they might be very different. 

It's also causing troubles when extracting ftrack data for deadline as they only get extracted for the first processed instance.

**Comment by tokejepsen** [comment]
Do we want to continue with adding to a common data member in context for optional global items, like; ```job_data['Pool'] = 'medium'```?
The other option is to have lots of deadline prefixed data members, which would make it more fixed but maybe easier to document/understand, ei. ```deadlineJobPool = 'medium'```.

**Comment by mkolar** [comment]
I think that every data member should be created per instance. So each instance should have it's own job_data and plugin_data. So every write node, mantra node etc is it's own independent job

**Comment by tokejepsen** [comment]
And what is your suggestion for shared optional data?

We could have the optional plugins be selectors, which makes more sense since they are gathering data, we'll then offset the host selector to inject the data from the optional plugins.

**Comment by mkolar** [comment]
I wouldn't make any of this data shared. Every instance should have it's own copy of job_data and plugin_data, even if most of it is a duplicate. The point is to be able to potentially submit 2 or more completely different jobs. 

Example:
I might want to have different pool, group. priority based on whether it's a prerender or final render write node. 

Every deadline_extension plugins should operate on instance, rather than context

**Comment by tokejepsen** [comment]
fixed in #15
