### ISSUE TITLE
merge extract_dealine_draft plugins

### ISSUE THREAD

**Issue by mkolar** [pyblish/pyblish-deadline#13]
There are 3 extract_deadline_draft plugins (vanilla, maya, nuke).

They practically do the same thing apart from setting the width and height of the frame. I think thse can easily be merge to just one plugin. To deal with the width and height then we could either do it by querying hosts and running different snippets based on that, or even omit the attributes altogether. I'm quite certain that deadline doesn't need either of them.

**Comment by mkolar** [comment]
Ups sorry my bad, I've just realised, that draft of course need width and height (depending on the template used), So I reckon we should deal with it based on hosts, but in the same plugin.

**Comment by tokejepsen** [comment]
There is also the option of getting this data in the selector, so we are keeping the host specific code in selectors.

**Comment by mkolar** [comment]
even better

**Comment by mkolar** [comment]
I've done this and some other issues that I started here in my repo. I'll send a pull request soon so we can discuss it there.

**Comment by tokejepsen** [comment]
fixed in #15

**Comment by mottosso** [comment]
@tokejepsen is on fire! :dancer:

**Comment by tokejepsen** [comment]
> @tokejepsen is on fire! :dancer:

More like @mkolar was, and I'm just merging:)
