### ISSUE TITLE
Delete temporary submission files

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-deadline#16]
Currently the extension is writing temporary submission files to disk. These are purely for submission and the data is visible in the Monitor afterwards, so we don't need to keep these.

**Comment by mottosso** [comment]
Was it fixed?

**Comment by tokejepsen** [comment]
What has been specified in the issue, which is to delete the temporary files.

**Comment by mottosso** [comment]
Not "what" was fixed, but "was" it fixed. You closed it without saying. :) It could have been discarded, or superseded by another issue.

**Comment by tokejepsen** [comment]
ahh, need to read the comments clearer:)
