### ISSUE TITLE
Make "deadlineData" a list

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-deadline#20]
If "deadlineData" is a list of dictionaries, we could submit multiple jobs per instance.

**Comment by mottosso** [comment]
The Context is already a list and is intended for exactly this. :)

**Comment by tokejepsen** [comment]
The problem with putting it in the context, is that its not instance specific.

We have talked about making this extension more like the ftrack extension, which makes sense so developers can use it how ever they want, and merely be a plugin development workflow with some convinience plugins. By having the "deadlineData" data member be a list, we can be fully flexible for the needs ahead.

The current case for this is in Hiero if you want to output multiple transcode jobs to the farm.

**Comment by mottosso** [comment]
I'm probably just not understanding those needs, it sounds like you are subdividing an Instance which is already a subdivision of the Context.

An Instance is designed to be the inverse of a file or sequence of files. As in, when you import a single asset into Nuke, Maya, Hiero or Houdini et. cetera the resulting nodes *is* the instance. I'm having trouble seeing how this analogy would work when producing multiple sequences for a single Instance. Could you help me out? Have you considered making more Instances? Pyblish itself is designed to handle loads of Instances. If the trouble is sharing data, then perhaps share it through the Context?

**Comment by tokejepsen** [comment]
Thinking more about it, having "deadlineData" as a list might not be very good as you would be able to distinguish the two items in the list.

I'll investigate different instances for the Hiero pipeline. Thanks for the discussion @mottosso :)
