### ISSUE TITLE
Account for having remote and local submission

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-deadline#23]
If both remote and local is setup, two jobs will get submitted.

Need to continue to local submission if remote fails. Else return.

**Comment by tokejepsen** [comment]
@mottosso thought having "fixes #23" in the commit would auto close the issue?

**Comment by mottosso** [comment]
I think it only reacts to certain keywords, possibly "fixed" instead of "fixes". Not sure, you might have to Google about it.
