### ISSUE TITLE
Support for multiple Draft outputs

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-deadline#7]
Currently the default implementation of Draft only takes in one template per job. With some simple modifications, Draft could support multiple outputs, so an image sequence could output high and low resolutions on different jobs.

The thinking is to have a list of draft templates in the submission parameters.

**Comment by mkolar** [comment]
That would be useful and quite simple to do as well.

**Comment by tokejepsen** [comment]
Turns out most of the work is done in the Draft Event plugin. I've implemented a version here, and all I'm doing is injecting more data into the job data;

```python
job_data = {}
if instance.has_data('deadlineJobData'):
    job_data = instance.data('deadlineJobData').copy()

extra_info_key_value = {}
if 'ExtraInfoKeyValue' in job_data:
    extra_info_key_value = job_data['ExtraInfoKeyValue']

extra_info_key_value['DraftTemplates0'] = r'K:/tools/Deadline/draft-templates/MPEG4_full_alexaToSRGB.py'
extra_info_key_value['DraftTemplates1'] = r'K:/tools/Deadline/draft-templates/DNXHD_1080_alexaToSRGB_32mb.py'
```

Closing this issue as studios can implement this in their own deadline extractor.
